### ISSUE TITLE
build jdk 1.8

### ISSUE THREAD

**Issue by cbsistem** [tedchoward/ThinWire#4]
hello !! is possible build in jdk 1.8 ?

exists howto .  tanks

**Comment by tedchoward** [comment]
Yes, it should build just fine with JDK 1.8. Check out the source and type `mvn package` to build the jar.

**Comment by cbsistem** [comment]
you use Thinwire in production?

**Comment by tedchoward** [comment]
I haven't in a very long time. I was part of the team that originally built this framework. Our company used it to build a commercial lending product that major banks used. I left that job 9 years ago to pursue a startup. I'm not sure if they still use it internally, but they quit maintaining the open source project, so I put it up over here.

Every once in a while, I'll mess with it, but it's a hobby for me.

**Comment by cbsistem** [comment]
Build all projects use jdk 1.8
